apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jenkins
  name: jenkins
  namespace: shared-services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkins
    spec:
      containers:
      - image: us.gcr.io/jimmy-359009/jenkins
        name: jenkins
        livenessProbe:
          exec:
            command:
            - echo "hi"
          initialDelaySeconds: 3
          periodSeconds: 3
        resources: {}
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nexus
  name: nexus
  namespace: shared-services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nexus
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nexus
    spec:
      containers:
      - image: us.gcr.io/jimmy-359009/nexus
        name: nexus
        livenessProbe:
          exec:
            command:
            - echo "hi"
          initialDelaySeconds: 3
          periodSeconds: 3
        resources: {}
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: us.gcr.io/jimmy-359009/nginx
        name: nginx
        livenessProbe:
          exec:
            command:
            - echo "hi"
          initialDelaySeconds: 3
          periodSeconds: 3
        resources: {}
status: {}